services:
  config:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - ${HS_CONFIG_PORT:-8380}:8888
    environment:
      HS_CONFIG_SEARCH_LOCATIONS: file:/var/hs/config
    volumes:
      - "./config:/var/hs/config"
